#!/usr/bin/env bash
# Bash script that displays Best School 10 times,
# but for the 9th iteration, displays Best School and then Hi on a new line.

counter=1
while [ $counter -le 20 ];
do
	case $counter in
		4)
			echo "$counter"
                	echo "bad luck from China";;
		9)
			echo "$counter"
                	echo "bad luck from Japan";;
		17)
			echo "$counter"
                        echo "bad luck from Italy";;
		*)
			echo "$counter"
			;;
	esac
	((counter++))
done
