#!/usr/bin/env bash
# this code goes to the hosts file and changes the IP of the localhost	
cp /etc/hosts ~/hosts.new
sed -i 's/^127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
